### ISSUE TITLE
Working very well in Skyrim except for side to side movement

### ISSUE THREAD

**Issue by gormanj** [pottedmeat7/OpenVR-WalkInPlace#16]
Latest update working very well in Skyrim with and without trackers.

I noticed that Skyrim is implementing a sidestepping (or maybe turning, I'm not sure) with the slightest wand movements. I've never noticed it before because I was standing still. However, when you are walking it causes you to weave from side to side. This almost definitely is not a WIP issue, but it would be great to somehow disable that function in Skyrim if anyone knows how, because although WIP really helps immersion, the side-to-side movement does break it a bit.

I suggest more of us support this project, it is by far the best walking solution because it simply makes a lot of sense to recognize patterns in how we walk normally instead of us using forced artificial means such as over emphasized arm swings. Great work!

Please support this impressive project:
http://www.patreon.com/pottedmeat7

**Comment by pottedmeat7** [comment]
Hi @gormanj yes I dont think this WIP system will cause any side to side effect and haven't seen that issue before. I will close this issue for now, unless there is something that could be done in WIP to help side to side but that sounds much more like it could change from game to game.
