### ISSUE TITLE
OpenVR-WalkInPlace for Skyrim Not working in Windows Mixed Reality (WMR)

### ISSUE THREAD

**Issue by Bortronx** [pottedmeat7/OpenVR-WalkInPlace#19]
I have tested it only only on Skyrim using the Samsung Odyssey headset. The software is detects position and shows tracking data but there is no movement whatsoever. I tried using both trackpad and keyboard movement. However, WMR does not use the trackpad for movement like the vive does, it uses the sticks. Using the keyboard was also unsuccessful.

**Comment by pottedmeat7** [comment]
If you view the graph, are you seeing the yellow lines indicating it detected a step?

**Comment by Bortronx** [comment]
@pottedmeat7  No, I do not see the yellow lines indicating the step. Here is an image of what I see in the graph view:  [https://i.imgur.com/gY3FlWw.jpg](url).

**Comment by pottedmeat7** [comment]
Looks like its getting no tracking values from the HMD. This would not allow the data needed to trigger a step.

**Comment by Bortronx** [comment]
Oh I see thanks.

**Comment by RADRaze2KX** [comment]
Is this still the case? Is there a workaround? I can't seem to get any of these locomotion softwares to work with the Odyssey+.
