### ISSUE TITLE
Does this work with WMR 

### ISSUE THREAD

**Issue by sabejithepirate** [pottedmeat7/OpenVR-WalkInPlace#27]
I have been trying to get this set up for a while and can't seem to get it working. the trackers show fine on the graph but the headset never seems to move on the graph, I have tried reinstalling openvr steam vr and windows mixed reality for steam. can windows headsets just not be tracked at all? or I'm I doing something wrong.

**Comment by pottedmeat7** [comment]
No I do not think that the support for WMR will happen until OpenVR provides documentation on how to do that. For some reason OpenVR does not receive the values through SteamVR as the same as the Vive.
