### ISSUE TITLE
Headset type and Tracker checkbox always reset

### ISSUE THREAD

**Issue by catbert7** [pottedmeat7/OpenVR-WalkInPlace#36]
Everything else I can save in a profile but, every time I start up SteamVR or load a profile, the headset type always reverts back to WMR and the tracker box always gets checked on. Just a minor annoyance ;)

**Comment by pottedmeat7** [comment]
Ok fixed these issues and have a new release, You will have to delete and recreate your profiles for it to work. Start with deleting your default one (if you have one) and the settings wont reset, when recreating.

**Comment by pottedmeat7** [comment]
Sorry thought I had fixed the tracker box, but it was a more elusive bug. Made the quick change on the latest release.
