### ISSUE TITLE
Speed getting stuck after changing settings

### ISSUE THREAD

**Issue by catbert7** [pottedmeat7/OpenVR-WalkInPlace#37]
When I change some of the settings, the speed gets locked to jog or run for a while afterward and I can't switch to walking until it resolves itself. Haven't been able to determine exactly what resolves it but it doesn't seem to be time. If I just keep turning WiP on/off with the optional activation button (hold grip to activate, in my case) and moving at walk speed it starts working after 5-10 seconds (it will only do run speed until then). Again, a minor annoyance ;) If I figure out anything more about it, I'll update you.

**Comment by pottedmeat7** [comment]
Yes noticed this bug also. It is now fixed in the latest release.

**Comment by pottedmeat7** [comment]
Ok just realized this still happens with running. Its difficult to test, especially because Skyrims sprint function, which causes other issues. But jogging slowing to walking does work now.
