### ISSUE TITLE
Manually Change Settings

### ISSUE THREAD

**Issue by ClancyDamon** [pottedmeat7/OpenVR-WalkInPlace#4]
Whenever I try to manually change the options (in VR, by clicking the actual number in the menu) it looks like all of the options are changed. For example, for testing my settings, I highlighted the HMD Pitch Down and tried to change it to 60. Once I confirmed on the VR keyboard, I found that the HMD Pitch Up was also 60, and the Step HMD Y, Step HMD XZ, Hand Jog, and Hand Run were all set to what I assume are maximum values. This is happening with the latest version, 2.3.

**Comment by pottedmeat7** [comment]
Hi ClancyDamon, this should be fixed in 2.4
