### ISSUE TITLE
Enable / disable multiple trackers

### ISSUE THREAD

**Issue by artimage25** [pottedmeat7/OpenVR-WalkInPlace#40]
Hello, first of all thank you for the great work done with this fantastic addon.

I would like to make a suggestion that may not be very complicated.

In my case I use different trackers for different functions:
- I always use a tracker for my hyperkin hyperblaster gun
- use 2 trackers for the feet with which I use Walkinplace
- sometimes I use another 2 trackers for the wrists of the hands
- sometimes I use a hip tracker that I also use for Walkinplace
It would be necessary to enable / disable which trackers we want to use in Walkinplace (2 trackers in the feet or 1 tracker in the hip) and to be able to continue using the rest of the trackers without interfering in Walkinplace.

Thank you very much and encourage your work in the addon.

**Comment by artimage25** [comment]
I think that will not work well, since precisely the games that use the live tracker as a weapon only work with the first tracker they find. For example with the game PractiSim VR only works if the tracker in the Hyperblaster is the first one that turns on.
The most practical way I think it would be a drop-down menu of controllers and trackers in the style of the Input Emulator to activate/deactivate the devices id you want to use. That way you could also for example use a controller on the hip if you do not have a tracker.
Regards

**Comment by pottedmeat7** [comment]
Oh guess they had a similar idea. I would have to come up with another way, but I'll consider adding it as a feature

**Comment by artimage25** [comment]
Thanks

**Comment by pottedmeat7** [comment]
The new release allows you to select a different order of enabled devices. Three new release works better without trackers at all so I haven't really tested every feature, plus I only have two trackers. However it should work to enable only a 3rd or 4th tracker too.
