### ISSUE TITLE
Suggestions, disable track pad.

### ISSUE THREAD

**Issue by generalsumthing** [pottedmeat7/OpenVR-WalkInPlace#44]
I love this program, it's so immersive that I don't like playing anything without it lol but I will occasionally graze the touch pad witch actually breaks my immersion!
Why not disable the physical track pad?

**Comment by pottedmeat7** [comment]
I actually totally agree with this. I would probably have to make it optional as it may annoy some people. I put a bit of effort into trying to add this but really its a bit harder to disable input then to add additional input. However this will eventually work with some updates in OVRWIP and some configuration in Steam's VR Input system.

**Comment by generalsumthing** [comment]
Glad to hear it's not just me lol I know it's a work in progress and this particular function would probably be a last priority way down the road.
I really do love this program.
Another idea I was thinking about was inertia.
The world moves, but your holding still.
That's what gives most people motion sickness.
But also sudden starting and stopping.
Going from zero to a hundred instantaneously is also a bit jarring.
I think it would be better if eventually you could add a small delay.
That once you started walking it would slowly speed up to the selected speed.
Even if it would take just a second to go from zero to the selected jog speed I think it would greatly increase comfort for people prone to vr sickness.
