### ISSUE TITLE
No movement in any games using WMR headset

### ISSUE THREAD

**Issue by dara-mtl** [pottedmeat7/OpenVR-WalkInPlace#45]
Hi, I've tried this program with the latest SteamVR (1539100633), a Lenovo Explorer Headset and Windows 10 build 1803 (17134.320). I've installed WIP via the installer and could see it on the SteamVR dashboard. I activated it as instructed and went in the graph section and saw both the headset and controllers were picking up clear movement, however none of the games I've tried worked with it.

Only Gorn had movement upon activation, but it was just moving forward without any means to stop it. I tried to change several settings and read all the info I could find carefully. I also tried to use the other SteamVR versions still available, with no success. 

The log mention a long list of mapping problems such as this one:

"[INFO ] 2018-10-31 18:50:40: New client connected: endpoint "driver_vrwalkinplace.client_queue.1914551630", cliendId 7
[WARN ] 2018-10-31 18:50:40: Device 2: No mapping from axis id 1 to input component." 

either for device 2 or device 1.

I see the last version of WIP date from 31st July. Could it be a compatibility issue with the newest SteamVR/WMR or am I missing something?

Thanks in advance!

**Comment by pottedmeat7** [comment]
Release 4.0 should support WMR. The controller input can be rebound in the SteamVR Input Rebinding system to WMR input.
