### ISSUE TITLE
auto configure doesn't work properly on WMR

### ISSUE THREAD

**Issue by dara-mtl** [pottedmeat7/OpenVR-WalkInPlace#49]
Thank you for your fantastic work, this is very much appreciated. The new options makes "walking" feels very natural, however there are a few options that doesn't work, at least with a WMR headset. When trying the auto configure option, the "walking phase" at the start doesn't detect any movement but the "jogging phase" and "running phase" are working normally. If the auto configure is cancelled or interrupted, it is not possible to re-run it without having to restart steamVR, or else it's stay stuck on the "walking phase" and cause blackout on the display for a few seconds, once in while, until steamVR ends up crashing. The other options  ##to enable/disable WIP doen't seems to work either.

I use steamVR 1.1.4 with the lastest version of Windows 10. Please let me know if there are any other info or log I can give to help.

**Comment by pottedmeat7** [comment]
This work better on more recent releases. If tracking data is visible for jogging/running it should also have output for walking. The recent releases are more stable and should not have as many issues with WMR, but there may be some issues with reliable tracking detection..
