### ISSUE TITLE
I see an HTC vive controller in front of my WMR controller

### ISSUE THREAD

**Issue by p4cm4n** [pottedmeat7/OpenVR-WalkInPlace#51]
As title says I see both controllers instead of mine only, i can provide screenshots or logs if needed.

**Comment by pottedmeat7** [comment]
I thought I noticed this too. Although I use vive controllers so I couldn't tell the difference as much, but it looked like it was rendering the model over the other one. 
The treadmill controller just does this by default, which in most ways is very nice, as it does emulate the physical controllers in a way. The double rendering though is unnecessary and annoying. 
There may be a way to replace the model with a "invisible" model, but it would take creating that and inserting it into "C:\Program Files (x86)\Steam\SteamApps\common\SteamVR\resources\rendermodels\"

**Comment by pottedmeat7** [comment]
This is fixed in the latest release
