### ISSUE TITLE
vcvarsall.bat is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Blindmikey** [pottedmeat7/OpenVR-WalkInPlace#6]
when running the step:
```b2 toolset=msvc-14.0 address-model=64```

The error ```"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx86/vcvarsall.bat"' is not recognized as an internal or external command, operable program or batch file.``` appears several times. Build ends with 
```1 file(s) copied.
...failed updating 6 targets...
...skipped 4 targets...
...updated 1190 targets...
```

Is this crucial?

**Comment by pottedmeat7** [comment]
You need to use the VS2017 Native tools command prompt to run this otherwise it has trouble finding the VS tools
