### ISSUE TITLE
Can't work with WASD control for non-steam app

### ISSUE THREAD

**Issue by kimsama** [pottedmeat7/OpenVR-WalkInPlace#63]
Hey, 

I'm trying to use OpenVR-WalkInPlace with non-steam app using WASD control but it doesn't work as expected. 

I just installed only OpenVR-WalkInPlace app for that. 
Is there any missing setting or installation to work an app which is not a steam game?

Or it would be appreciated if you let me know any step by step tutorial I can refer. 

Thanks much.

**Comment by pottedmeat7** [comment]
SteamVR, with SteamVR supported hardware, must be running for this application to be used.
