### ISSUE TITLE
Keyboard input for naming models/profiles does not work

### ISSUE THREAD

**Issue by doxxx** [pottedmeat7/OpenVR-WalkInPlace#64]
When I go to create a new model or profile and it asks for a name, I can get the SteamVR keyboard to popup and enter a name but, after pressing Done, the name does not get entered into the model/profile name field.

Since this is the first time I'm using the app, this is preventing me from creating a model or profile and thus I cannot use the app at all.

OpenVR-WalkInPlace version: 4.3
Controllers: Index
SteamVR: beta 1.9.7

**Comment by pottedmeat7** [comment]
If the SteamVR keyboard is not working for input, which in SteamVR beta 1.9.7 I can confirm it isn't, you can launch the interface in desktop mode with the batch script `C:\Program Files\OpenVR-WalkInPlace\startdesktopmode.bat` 
Then you can enter text fields with normal keyboard. 
I will look into the VR keyboard bug and see if theres anything I can do. Or SteamVR will hopefully have a fix for this problem before releasing the beta...

**Comment by doxxx** [comment]
Thanks, starting it in desktop mode let me create the model and profile.

**Comment by pottedmeat7** [comment]
This seems to be fixed in the latest SteamVR beta

**Comment by doxxx** [comment]
Yes, confirmed. Thanks.
