### ISSUE TITLE
Can not create new Data Model - (keyboard not working)

### ISSUE THREAD

**Issue by Ravenwynne** [pottedmeat7/OpenVR-WalkInPlace#69]
Can't create a New Data Model because the dialogue box requesting a new Data Model "Name" brings up a keyboard that is unresponsive, and won't allow you to create a name.  Can't save a new model with no name.

Not sure when this started happening - probably with the new version of Steam.

**Comment by pottedmeat7** [comment]
I am having troubles with the overlay keyboard also. Mine does come up but it shows up behind the overlay, so I kind of have to duck to see and use it. 
I do notice, what may seem like unresponsiveness, that when you type it's not changing the text field on the overlay. 
But the text does appear after I push then 'done' 
Try that and let me know if it works. 
There were changes to the overlay API so will probably need an update to fix completely.
