### ISSUE TITLE
Same as previous- No steps taken for FO4 or Gorn. Graph works. 

### ISSUE THREAD

**Issue by LonginusHeart** [pottedmeat7/OpenVR-WalkInPlace#8]
I've tried Gorn as well and the graph works but I'm not getting any movement. Am I installing incorrectly? Should I be doing anything other than running your installer?

I'm running the OpenVR emulation for Fo4 so I've got your OVRIE installer. I'm also using your screenshotted settings for everything. The trackpad emulation works just fine. Steam VR isn't in beta. 

Thanks for your help on this

**Comment by pottedmeat7** [comment]
Sorry, it seems as though there is some issue with the driver callbacks. It works on some setups..., there will probably be more updates to SteamVR and more documentation to allow other ways to callback to devices.

**Comment by LonginusHeart** [comment]
Totally understandable. Thank you for the quick response. You seem like a good person

**Comment by pottedmeat7** [comment]
Is this still an issue? Does the new release work?
